spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders:
              - Authorization
              - content-type
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/master
        registration:
          keycloak:
            client-secret: 928b57f4-f603-4aed-9b4d-acc47c09e5d2
            client-id: gateway
      resource:
        jwk:
          key-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs
eureka:
  client:
    fetchRegistry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8900